### ISSUE TITLE
isPresentedModally in PPOverlayContainerViewController returns YES always even if presented by navigation view controller.

### ISSUE THREAD

**Issue by varmeh** [microblink/blinkid-ios#18]
I am using sdk 1.3.0 on XCode 7.2.1. It always returns yes, even if it is pushed on to navigation view controller.

**Comment by juraskrlec** [comment]
Hi @varmeh 
thank you, this was indeed returning YES. New feature and fix for this problem will be in next release. 

Best,
Jura

**Comment by Cerovec** [comment]
Hi,

in v2.9.0 we removed that property entirely because it's not reliable (iOS allows multiple ways to present a VC, not just modal and non-modal).

As a replacement, we added additional properties to `PPUiSettings` object. 

```objective-c
/**
 * If YES, default camera overlay will display Cancel button.
 * Usually, if camera is displayed inside Navigation View Controler, this is reasonable to set to NO.
 *
 * Default: YES.
 */
@property (nonatomic, assign) BOOL showCloseButton;

/**
 * If YES, default camera overlay will display Torch button.
 * Usually, if camera is displayed inside Navigation View Controler, this is reasonable to set to NO.
 *
 * Default: YES.
 */
@property (nonatomic, assign) BOOL showTorchButton;

/**
 * If YES, default camera overlay will display Status bar.
 * Usually, if camera is displayed inside Navigation View Controler, this is reasonable to set to YES.
 *
 * Default: NO.
 */
@property (nonatomic, assign) BOOL showStatusBar;
```

Please let us know if this solves any potential problems you had. If it does, please close the issue.

**Comment by Cerovec** [comment]
Closed as solved. If it still persists on your end, @varmeh - please reopen the issue.
