### ISSUE TITLE
ERROR ITMS-90542: “Invalid CFBundleSupportedPlatforms value.”

### ISSUE THREAD

**Issue by benaneesh** [microblink/blinkid-ios#31]
Installed with Cocoapods, but ran into this error while submitting to the app store. Easy fix was going into the info.plist and deleting the key, and then submitting again.

<img width="536" alt="screen shot 2016-07-20 at 2 44 53 am" src="https://cloud.githubusercontent.com/assets/1724896/16992519/a70b6148-4e6d-11e6-8fbe-82f832028bc4.png">

**Comment by Pickles112358** [comment]
Thank you for reporting the error!
Yes, the fix is to delete the key from both .plist files (in framework and bundle). The keys will be removed in future releases
