### ISSUE TITLE
Swift Package Manager and BlinkID iOS 5.19.1

### ISSUE THREAD

**Issue by mapedd** [microblink/blinkid-ios#374]
Hello, It seems that something is broken with BlinkID SPM repo, when trying to use `5.19.1` I get download error in Xcode 14.

<img width="444" alt="Screenshot 2022-09-29 at 12 22 15" src="https://user-images.githubusercontent.com/422167/193007163-98e65bbe-53c6-4479-9d4e-3da8b6b929f9.png">

<img width="943" alt="Screenshot 2022-09-29 at 12 24 50" src="https://user-images.githubusercontent.com/422167/193007434-4a45244b-2f0b-471e-bce2-6a4165221c5d.png">

When using `5.18.0` it works fine. Is the package uploaded correctly? Or maybe links in the package are broken?

**Comment by MBrizic01** [comment]
Hello @mapedd 
The problem you are encountering is known to us; we are working on the bug fix for 5.19/5.19.1, so we temporarily removed it from GitHub. 

We will fix the issue in a couple of days. Meanwhile, you can use v 5.18.
Let me know if you have any additional questions.
Regards

**Comment by mapedd** [comment]
Hi, thanks for clarifying. Closing this one
