### ISSUE TITLE
Issue with OCR -- NY vertical DL, latest model

### ISSUE THREAD

**Issue by Vyyer** [microblink/blinkid-ios#387]
Hi,

NY vertical DL for U21 is not working for latest official template. Specifically, the DL I'm testing is a U21 non-federal ID issued 08/04/2022. I'm on version 5.20 but it looks like this wasn't part of the 6.00 release. 

Even on your official demo it is giving null results in the JSON output. 

Do you guys need a sample?

**Comment by MBrizic01** [comment]
Hello @Vyyer; thank you for reaching out. 

From our understanding, there are currently two different versions of new NY driver's licenses; a [Real ID ](https://townsquare.media/site/854/files/2022/03/attachment-thumbnail_image002_0.jpg?w=779&h=510&q=75)and an [Enhanced DL](https://townsquare.media/site/854/files/2022/03/attachment-thumbnail_image003.jpg?w=510&h=779&q=75).
We added support for the new DL (Real ID) in the [5.20](https://github.com/BlinkID/blinkid-ios/blob/master/Release%20notes.md#added-support-for-29-new-versions-of-already-supported-documents) release of BlinkId (not including vertical U21), and we will add the support for the Enhanced DL in v6.1 release (not including vertical U21 for now). 

I hope this helped; for further information regarding the possibility of adding support for non-supported documents, feel free to reach out to support@microblink.com
