### ISSUE TITLE
Support for iOS 12

### ISSUE THREAD

**Issue by yaakovgamliel** [microblink/blinkid-ios#391]
Could you please elaborate on why the SDK not longer supports iOS 12.

Thank you.

**Comment by MBrizic01** [comment]
Hello @yaakovgamliel; thank you for reaching out. We took into consideration various factors, but mainly we did to improve our SDK size, as now we can make some internal improvements which will additionally reduce it. It also enabled us to enhance our UI, as we can now detect dark/light mode. Also, based on the usage statistics, we considered that it was necessary to raise the iOS version to obtain needed improvements. I hope this helps!
