### ISSUE TITLE
License key expired 

### ISSUE THREAD

**Issue by sidrabasit** [microblink/blinkid-ios#396]
We received the below email notification, please let us know how it will impact the existing production application. I would also like to know if we need to update the license key before submitting the application update.
_The license in your private project has expired. If you want to continue using Microblink technology,  please send our sales team a message._

**Comment by somyaguptagit** [comment]
Hello,
Please let us know which license(starting LIC00...)  are you using in the project. We will renew the license from our end and you will only need to update the new key in the project.

**Comment by sidrabasit** [comment]
Thank you for your support.
