### ISSUE TITLE
Linker Errors in Xcode Project with BlinkID SDK

### ISSUE THREAD

**Issue by bhagwat8024** [microblink/blinkid-ios#403]
- Xcode version: 14.2
  - BlinkID SDK version: 2.18.2
  -problem: 

When attempting to build the Xcode project, we encounter linker errors related to the BlinkID SDK. The following undefined symbols are reported:

_OBJC_CLASS_$_PPBaseOverlayViewController
_OBJC_CLASS_$_PPBlinkInputRecognizerResult
_OBJC_CLASS_$_PPBlinkInputRecognizerSettings
_OBJC_CLASS_$_PPCameraCoordinator
_OBJC_CLASS_$_PPModernOcrResultOverlaySubview
_OBJC_CLASS_$_PPRecognizerResult
_OBJC_CLASS_$_PPRecognizerSettings
_OBJC_CLASS_$_PPRegexOcrParserFactory
_OBJC_CLASS_$_PPSettings
_OBJC_CLASS_$_PPViewControllerFactory
_OBJC_CLASS_$_PPVinOcrParserFactory
_OBJC_METACLASS_$_PPBaseOverlayViewController

These errors also persist in the sample app provided by the BlinkID SDK.

**Comment by MBrizic01** [comment]
Hello, @bhagwat8024. Is there a reason you are trying to build the project with a five-year-old SDK? 
This version and its recognizers are deprecated, and we highly recommend you use our latest version. If you encounter any issues with the newest version, don't hesitate to let us know, and we will happily assist you!

**Comment by bhagwat8024** [comment]
we are using this version since 5 years and we currently do not have plans for an upgrade...

**Comment by MBrizic01** [comment]
Hello, @bhagwat8024, thank you for your response. If you are our client, please reach out to support@microblink.com, so we can find the best solution for you. We do not support the implementation of such an old version. Thank you!

**Comment by bhagwat8024** [comment]
I got same issue with version 5.0.0
